# Generated by Django 4.0.3 on 2022-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_counselor_counselling_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='appoinments_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
