# Generated by Django 4.0.3 on 2022-03-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appoinment_req_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='req_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
