# Generated by Django 4.0.3 on 2022-03-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cls',
            new_name='Class',
        ),
    ]
