# Generated by Django 4.0.3 on 2022-03-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
    ]
