# Generated by Django 4.0.3 on 2022-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_article_image'),
        ('app', '0016_alter_article_image'),
    ]

    operations = [
    ]
