# Generated by Django 4.0.3 on 2022-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20220317_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
