# Generated by Django 4.0.3 on 2022-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_counselor_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
