# Generated by Django 4.0.3 on 2022-03-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_student_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
