# Generated by Django 4.0.3 on 2022-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_counselor_institute_alter_student_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='counselling_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='counselling_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
